 # Numpy : Dot Product

In [1]:
import pandas as pd
import numpy as np
import scipy as sp

In [2]:
import os,sys

In [3]:
print( os.curdir )
print( os.getcwd() )
print( os.path.abspath( os.getcwd() ) )

.
/Users/nururrahman/myRecSystem
/Users/nururrahman/myRecSystem


### Data

In [4]:
m1 = np.array([1,1,0,1,0,2,1,1,0]).reshape(3,-1)
m1

array([[1, 1, 0],
       [1, 0, 2],
       [1, 1, 0]])

In [5]:
m2 = m1.T
m2

array([[1, 1, 1],
       [1, 0, 1],
       [0, 2, 0]])

### Dot Product

In [6]:
np.dot(m1, m1)

array([[2, 1, 2],
       [3, 3, 0],
       [2, 1, 2]])

In [7]:
np.dot(m1, m2)

array([[2, 1, 2],
       [1, 5, 1],
       [2, 1, 2]])

In [8]:
np.corrcoef(m1)

array([[ 1.       , -0.8660254,  1.       ],
       [-0.8660254,  1.       , -0.8660254],
       [ 1.       , -0.8660254,  1.       ]])

In [9]:
m3 = m1/np.linalg.norm(m1)
np.dot(m3, m3.T)

array([[0.22222222, 0.11111111, 0.22222222],
       [0.11111111, 0.55555556, 0.11111111],
       [0.22222222, 0.11111111, 0.22222222]])

In [10]:
from scipy.spatial import distance
print( round(distance.cosine([1, 1, 0], [1, 0, 2]),2) )
print( distance.cosine([1, 1, 0], [1, 1, 0]) )

0.68
0.0
