# Pandas & Numpy : Array Element & Its Indices

In [1]:
import numpy as np
import pandas as pd

### Using Pandas

In [2]:
x = np.array(
    [[3, 1, 4],
     [1, 5, 9],
     [2, 6, 5]]
)

print('The Data :')
print(x)

The Data :
[[3 1 4]
 [1 5 9]
 [2 6 5]]


In [3]:
data = pd.DataFrame(x.T)
df = data.unstack(level=[0]).reset_index()
df = df.rename(columns={'level_0':'i', 'level_1':'j', 0:'comp'})
print( df )

   i  j  comp
0  0  0     3
1  0  1     1
2  0  2     4
3  1  0     1
4  1  1     5
5  1  2     9
6  2  0     2
7  2  1     6
8  2  2     5


### Using Numpy

In [4]:
x = np.array(
    [[3, 1, 4],
     [1, 5, 9],
     [2, 6, 5]]
)
print(x)

[[3 1 4]
 [1 5 9]
 [2 6 5]]


In [5]:
XX,YY = np.meshgrid(np.arange(x.shape[1]),np.arange(x.shape[0]))
print(XX)
print(YY)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [6]:
table = np.vstack( (YY.ravel(),XX.ravel(), x.ravel(order='C')) ).T
print(table)

[[0 0 3]
 [0 1 1]
 [0 2 4]
 [1 0 1]
 [1 1 5]
 [1 2 9]
 [2 0 2]
 [2 1 6]
 [2 2 5]]


In [7]:
for i in range(9):
    ij = table[:,1:3][i]
    print( ij[0], ij[1]  )

0 3
1 1
2 4
0 1
1 5
2 9
0 2
1 6
2 5


#### vstack, hstack, column_stack, concatenate

In [8]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [10]:
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [11]:
np.concatenate((a,b), axis=0)

array([1, 2, 3, 2, 3, 4])

In [12]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
np.hstack((a,b))

array([[1, 2, 3, 2, 3, 4]])

In [14]:
np.column_stack((a,b))

array([[1, 2, 3, 2, 3, 4]])

In [15]:
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])