 # SKLearn : Pairwise Distance

In [1]:
import pandas as pd
import numpy as np
import scipy as sp

In [2]:
import os, sys

In [3]:
print( os.curdir )
print( os.getcwd() )
print( os.path.abspath( os.getcwd() ) )

.
/Users/nururrahman/myRecSystem
/Users/nururrahman/myRecSystem


### Case 1 : Pairwise Distances with Rows of Original Matrix

In [4]:
m1 = np.array([1,1,0,1,0,2,1,1,0]).reshape(3,-1)

In [5]:
from sklearn.metrics import pairwise_distances

In [6]:
pairwise_distances(m1, m1, metric='euclidean')

array([[0.        , 2.23606798, 0.        ],
       [2.23606798, 0.        , 2.23606798],
       [0.        , 2.23606798, 0.        ]])

In [7]:
pairwise_distances(m1, m1, metric='cosine')

array([[0.00000000e+00, 6.83772234e-01, 2.22044605e-16],
       [6.83772234e-01, 0.00000000e+00, 6.83772234e-01],
       [2.22044605e-16, 6.83772234e-01, 0.00000000e+00]])

In [8]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(m1, m1)

array([[1.        , 0.31622777, 1.        ],
       [0.31622777, 1.        , 0.31622777],
       [1.        , 0.31622777, 1.        ]])

In [9]:
from sklearn.metrics.pairwise import pairwise_kernels
pairwise_kernels(m1, m1, metric='linear')

array([[2., 1., 2.],
       [1., 5., 1.],
       [2., 1., 2.]])

### Case 2 : Pairwise Distances with Rows of Transposed Matrix

In [10]:
m1 = np.array([1,1,0,1,0,2,1,1,0]).reshape(3,-1)

In [11]:
pairwise_distances(m1.T, m1.T, metric='euclidean')

array([[0.        , 1.        , 1.73205081],
       [1.        , 0.        , 2.44948974],
       [1.73205081, 2.44948974, 0.        ]])

In [12]:
pairwise_distances(m1.T, m1.T, metric='cosine')

array([[0.00000000e+00, 1.83503419e-01, 4.22649731e-01],
       [1.83503419e-01, 2.22044605e-16, 1.00000000e+00],
       [4.22649731e-01, 1.00000000e+00, 0.00000000e+00]])

In [13]:
cosine_similarity(m1.T, m1.T)

array([[1.        , 0.81649658, 0.57735027],
       [0.81649658, 1.        , 0.        ],
       [0.57735027, 0.        , 1.        ]])

### Case 3 : Pairwise Distances with Rows of Original Matrix and Transposed Matrix 

In [14]:
m1 = np.array([1,1,0,1,0,2,1,1,0]).reshape(3,-1)

In [15]:
pairwise_distances(m1, m1.T, metric='euclidean')

array([[1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.        , 3.        ],
       [1.        , 1.41421356, 1.41421356]])

In [16]:
pairwise_distances(m1, m1.T, metric='cosine')

array([[0.18350342, 0.5       , 0.29289322],
       [0.22540333, 0.0513167 , 1.        ],
       [0.18350342, 0.5       , 0.29289322]])

In [17]:
cosine_similarity(m1, m1.T)

array([[0.81649658, 0.5       , 0.70710678],
       [0.77459667, 0.9486833 , 0.        ],
       [0.81649658, 0.5       , 0.70710678]])

In [18]:
pairwise_kernels(m1, m1.T, metric='linear')

array([[2., 1., 2.],
       [3., 3., 0.],
       [2., 1., 2.]])

In [19]:
np.dot(m1, m1.T)

array([[2, 1, 2],
       [1, 5, 1],
       [2, 1, 2]])

### Subtracting Mean from Each Row 

In [20]:
row_mean = np.mean(m1, axis=1).reshape(m1.shape[0],1)
row_mean

array([[0.66666667],
       [1.        ],
       [0.66666667]])

In [21]:
m1 - row_mean

array([[ 0.33333333,  0.33333333, -0.66666667],
       [ 0.        , -1.        ,  1.        ],
       [ 0.33333333,  0.33333333, -0.66666667]])