In [1]:
import numpy as np
import pandas as pd

## Example 1

In [2]:
utility = np.array(
    [[3,4,3,1],
     [1,3,2,6],
     [2,4,1,5],
     [3,3,5,2]]
)

In [3]:
U, S, V = np.linalg.svd(utility, full_matrices=True)

In [4]:
print(U.shape, S.shape, V.shape)

(4, 4) (4,) (4, 4)


In [5]:
print(U)

[[-0.43124523  0.49315012 -0.55075835 -0.51719991]
 [-0.53273754 -0.53052572  0.41966021 -0.50854546]
 [-0.52374556 -0.40520071 -0.48729169  0.5692537 ]
 [-0.50587435  0.5578152   0.53206894  0.38708653]]


In [6]:
print(S)

[12.22151125  4.92815942  2.06380839  0.29766152]


In [7]:
print(V)

[[-0.3593326  -0.56750746 -0.4428526  -0.59388293]
 [ 0.36767659  0.08799758  0.56862492 -0.73057242]
 [-0.29605046 -0.62845599  0.65902357  0.28824492]
 [ 0.80501437 -0.52462823 -0.21502376  0.17459057]]


In [8]:
print(V.T)

[[-0.3593326   0.36767659 -0.29605046  0.80501437]
 [-0.56750746  0.08799758 -0.62845599 -0.52462823]
 [-0.4428526   0.56862492  0.65902357 -0.21502376]
 [-0.59388293 -0.73057242  0.28824492  0.17459057]]


#### Check

In [9]:
Sp = S*np.identity(4)
np.matmul( np.matmul(U,Sp), V)

array([[3., 4., 3., 1.],
       [1., 3., 2., 6.],
       [2., 4., 1., 5.],
       [3., 3., 5., 2.]])

In [10]:
alice = np.array([[5,3,4,4]])

In [11]:
Sp[0:2,0:2]

array([[12.22151125,  0.        ],
       [ 0.        ,  4.92815942]])

In [12]:
np.matmul( U[:,0:2], Sp[0:2,0:2] ) 

array([[-5.27046838,  2.43032242],
       [-6.51085779, -2.61451534],
       [-6.40096231, -1.99689367],
       [-6.18254905,  2.74900225]])

In [13]:
np.matmul( U[:,0:2], np.flip(Sp[0:2,0:2]) )

array([[-2.12524522,  6.02703977],
       [-2.6254155 , -6.48382611],
       [-2.58110164, -4.95216498],
       [-2.49302944,  6.81734479]])

In [14]:
np.matmul( alice, np.matmul( U[:,0:2], np.linalg.inv(Sp[0:2,0:2]) ) )

array([[-0.64418534,  0.30125475]])

## Example 2

In [15]:
utility = np.array(
    [[3,4,3,1],
     [1,3,2,6],
     [2,4,1,5],
     [3,3,5,2],
     [2,4,2,3]]
)

In [16]:
U, S, V = np.linalg.svd(utility, full_matrices=True)

In [17]:
print(U.shape, S.shape, V.shape)

(5, 5) (4,) (4, 4)


In [18]:
print(U)

[[-0.39382072  0.49212624 -0.43957909  0.05839415 -0.63724199]
 [-0.48098574 -0.53234963  0.47005676  0.31062125 -0.40965556]
 [-0.47670639 -0.40655167 -0.35918349 -0.67126706  0.16689671]
 [-0.45635021  0.55596836  0.57998722 -0.25130729  0.28827614]
 [-0.42196381  0.00552788 -0.34701428  0.62157039  0.56137984]]


In [19]:
print(S)

[13.4736313   4.92825029  2.23060476  0.44498448]


In [20]:
print(V)

[[-0.3583918  -0.59241428 -0.42644916 -0.58201526]
 [ 0.3672473   0.08832059  0.56734646 -0.73174237]
 [-0.23362023 -0.64241569  0.65816246  0.31550887]
 [-0.82589729  0.47806576  0.25115989 -0.16206636]]


In [21]:
print(V.T)

[[-0.3583918   0.3672473  -0.23362023 -0.82589729]
 [-0.59241428  0.08832059 -0.64241569  0.47806576]
 [-0.42644916  0.56734646  0.65816246  0.25115989]
 [-0.58201526 -0.73174237  0.31550887 -0.16206636]]


#### Check

In [22]:
Sp = np.zeros(20).reshape(5,4)
Sp[0,0] = S[0]
Sp[1,1] = S[1]
Sp[2,2] = S[2]
Sp[3,3] = S[3]
Sp

array([[13.4736313 ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  4.92825029,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.23060476,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.44498448],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [23]:
np.matmul( np.matmul(U,Sp), V)

array([[3., 4., 3., 1.],
       [1., 3., 2., 6.],
       [2., 4., 1., 5.],
       [3., 3., 5., 2.],
       [2., 4., 2., 3.]])